const projects = [
  {
    id: 1,
    category: 'basic',
    title: 'coffee junkie',
    techUsed: ['HTML only'],
    desc: 'A basic project using HTML only to understand the various HTML elements and attributes.',
    url: 'https://coffee-junkie-html.netlify.app/',
    image: '../projects-img/coffee.jpg',
  },
  {
    id: 2,
    category: 'basic',
    title: 'cards project',
    techUsed: ['HTML', 'CSS'],
    desc: 'Making card design using CSS fundamental properties like position, float and width to make column layout',
    url: 'https://css-cards-style.netlify.app/',
    image: '../projects-img/cards.jpg',
  },
  {
    id: 3,
    category: 'basic',
    title: 'tea station',
    techUsed: ['HTML', 'CSS'],
    desc: 'A website for a company named "Tea Station". Project based on mainly CSS flexbox model to make various layout. It uses animations and some JavaScript to add basic functionality like toggle sidebar and footer date.',
    url: 'https://tea-station-gkc.netlify.app/',
    image: '../projects-img/tea-station.jpg',
  },
  {
    id: 4,
    category: 'featured',
    title: 'backroad tour',
    techUsed: ['HTML', 'CSS'],
    desc: 'This project uses CSS Grid model for the layout',
    url: 'https://backroad-tour-test.netlify.app/',
    image: '../projects-img/backroad.jpg',
  },
  {
    id: 5,
    category: 'basic',
    title: 'Grid mini project',
    techUsed: ['HTML', 'CSS'],
    desc: 'About project',
    url: 'https://grid-mini-pj.netlify.app/',
    image: '../projects-img/grid-mini.jpg',
  },
  {
    id: 6,
    category: 'featured',
    title: `John's portfolio`,
    techUsed: ['HTML', 'CSS'],
    desc: 'About project',
    url: 'https://john-portfolio-demo.netlify.app/',
    image: '../projects-img/john-folio.jpg',
  },
  {
    id: 7,
    category: 'basic',
    title: 'color flipper',
    techUsed: ['HTML', 'CSS', 'JavaScript'],
    desc: 'About project',
    url: 'https://color-flipper-magic.netlify.app/',
    image: '../projects-img/color-flipper.jpg',
  },
  {
    id: 8,
    category: 'basic',
    title: 'giveaway countdown timer',
    techUsed: ['HTML', 'CSS', 'JavaScript'],
    desc: 'About project',
    url: 'https://giveaway-timer.netlify.app/',
    image: '../projects-img/timer.jpg',
  },
  {
    id: 9,
    category: 'featured',
    title: 'Gallery',
    techUsed: ['HTML', 'CSS', 'JavaScript'],
    desc: 'About project',
    url: 'https://pradeep-jais.github.io/Gallery/',
    image: '../projects-img/gallery.jpg',
  },
  {
    id: 10,
    category: 'basic',
    title: 'Filters',
    techUsed: ['HTML', 'CSS', 'JavaScript'],
    desc: 'About project',
    url: 'https://filter-button-pj.netlify.app/',
    image: '../projects-img/filters-btn.jpg',
  },
  {
    id: 11,
    category: 'basic',
    title: 'Random User API',
    techUsed: ['HTML', 'CSS', 'JavaScript'],
    desc: 'About project',
    url: 'https://random-user-apis.netlify.app/',
    image: '../projects-img/random-user.jpg',
  },
  {
    id: 12,
    category: 'featured',
    title: 'cocktail store',
    techUsed: ['HTML', 'CSS', 'JavaScript'],
    desc: 'About project',
    url: 'https://my-cocktail-store.netlify.app/',
    image: '../projects-img/cocktails.jpg',
  },
  {
    id: 13,
    category: 'featured',
    title: 'pagination',
    techUsed: ['HTML', 'CSS', 'JavaScript'],
    desc: 'About project',
    url: 'https://css-cards-style.netlify.app/',
    image: '../projects-img/pagination.jpg',
  },
  {
    id: 14,
    category: 'featured',
    title: 'calculator',
    techUsed: ['HTML', 'CSS', 'JavaScript'],
    desc: 'About project',
    url: 'https://calculator-basic-js.netlify.app/',
    image: '../projects-img/calci.jpg',
  },
];
